### ISSUE TITLE
Puppet manifests not found

### ISSUE THREAD

**Issue by sid3windr** [AutomatingJunosAdministration/examples#2]
Although the book, on page 508, points to this repository for the full set of example Puppet manifest files, they seem to be missing from the repository currently.

**Comment by stacywsmith** [comment]
Hi @sid3windr,

I'm sorry for the omission. Thanks for pointing it out.
I have now committed the Puppet example files.

https://github.com/AutomatingJunosAdministration/examples/tree/master/puppet
